Change floor to exclude values smaller than 0.01
nation3/nationcred-instance pull request #73
Opened 2022-07-11 15:00 UTC by johnmark13

2022-07-12 00:03 UTC, aahna-ashina requested changes
Shouldn't these code changes also cause changes in the existing CSV files?

2022-07-12 07:36 UTC, johnmark13 commented
Yep, they will, and they do, I just wanted to keep the PR clean for now. Do you want me to change the floor to 0.00125 and regenerate the files?

2022-07-13 05:33 UTC, aahna-ashina commented on generate-csv.js
> +const FLOOR = 0.00125;
```suggestion
// 0.50% of the budget in `config/grain.json`
const FLOOR = 0.00125;
```

2022-07-13 12:28 UTC, xPi2 approved these changes

2022-07-13 16:24 UTC, merged